language: php
php:
  - '7.4'
install:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  # minimal required coverage is set to 80+ %
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose
